/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 107
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 77
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 20
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 22
#define SUPERTYPE_COUNT 2

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_for = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_if = 5,
  anon_sym_they = 6,
  anon_sym_can = 7,
  anon_sym_cannot = 8,
  anon_sym_because = 9,
  anon_sym_COMMA = 10,
  sym_wildcard = 11,
  anon_sym_or = 12,
  anon_sym_and = 13,
  anon_sym_not = 14,
  anon_sym_BANG = 15,
  anon_sym_LPAREN = 16,
  anon_sym_RPAREN = 17,
  anon_sym_check = 18,
  anon_sym_with = 19,
  anon_sym_EQ = 20,
  anon_sym_ATcontext = 21,
  anon_sym_ATcolumn = 22,
  anon_sym_DOT = 23,
  anon_sym_ATsql = 24,
  anon_sym_SQUOTE = 25,
  anon_sym_DQUOTE = 26,
  aux_sym_string_content_token1 = 27,
  aux_sym__double_quoted_content_token1 = 28,
  sym_escape_sequence = 29,
  sym_float = 30,
  sym_integer = 31,
  anon_sym_true = 32,
  anon_sym_false = 33,
  sym_null = 34,
  sym_named_binding = 35,
  sym_positional = 36,
  sym_comment = 37,
  sym_source_file = 38,
  sym_schema_header = 39,
  sym_schema_block = 40,
  sym_block_body = 41,
  sym_rule = 42,
  sym_condition_clause = 43,
  sym__clause = 44,
  sym_can_clause = 45,
  sym_cannot_clause = 46,
  sym_because_clause = 47,
  sym_ability_list = 48,
  sym_ability = 49,
  sym__expression = 50,
  sym_or_expression = 51,
  sym_and_expression = 52,
  sym_not_expression = 53,
  sym_parenthesized_expression = 54,
  sym_can_expression = 55,
  sym_check_expression = 56,
  sym_handle = 57,
  sym_with_clause = 58,
  sym_with_entry = 59,
  sym_condition = 60,
  sym_argument_list = 61,
  sym__argument = 62,
  sym_context_ref = 63,
  sym_column_ref = 64,
  sym_sql_ref = 65,
  sym_string = 66,
  sym_string_content = 67,
  aux_sym__double_quoted_content = 68,
  sym_boolean = 69,
  aux_sym_source_file_repeat1 = 70,
  aux_sym_block_body_repeat1 = 71,
  aux_sym_rule_repeat1 = 72,
  aux_sym_ability_list_repeat1 = 73,
  aux_sym_with_clause_repeat1 = 74,
  aux_sym_argument_list_repeat1 = 75,
  aux_sym_string_content_repeat1 = 76,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_for] = "for",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_they] = "they",
  [anon_sym_can] = "can",
  [anon_sym_cannot] = "cannot",
  [anon_sym_because] = "because",
  [anon_sym_COMMA] = ",",
  [sym_wildcard] = "wildcard",
  [anon_sym_or] = "or",
  [anon_sym_and] = "and",
  [anon_sym_not] = "not",
  [anon_sym_BANG] = "!",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_check] = "check",
  [anon_sym_with] = "with",
  [anon_sym_EQ] = "=",
  [anon_sym_ATcontext] = "@context",
  [anon_sym_ATcolumn] = "@column",
  [anon_sym_DOT] = ".",
  [anon_sym_ATsql] = "@sql",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_content_token1] = "string_content_token1",
  [aux_sym__double_quoted_content_token1] = "_double_quoted_content_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_float] = "float",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [sym_named_binding] = "named_binding",
  [sym_positional] = "positional",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_schema_header] = "schema_header",
  [sym_schema_block] = "schema_block",
  [sym_block_body] = "block_body",
  [sym_rule] = "rule",
  [sym_condition_clause] = "condition_clause",
  [sym__clause] = "_clause",
  [sym_can_clause] = "can_clause",
  [sym_cannot_clause] = "cannot_clause",
  [sym_because_clause] = "because_clause",
  [sym_ability_list] = "ability_list",
  [sym_ability] = "ability",
  [sym__expression] = "_expression",
  [sym_or_expression] = "or_expression",
  [sym_and_expression] = "and_expression",
  [sym_not_expression] = "not_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_can_expression] = "can_expression",
  [sym_check_expression] = "check_expression",
  [sym_handle] = "handle",
  [sym_with_clause] = "with_clause",
  [sym_with_entry] = "with_entry",
  [sym_condition] = "condition",
  [sym_argument_list] = "argument_list",
  [sym__argument] = "_argument",
  [sym_context_ref] = "context_ref",
  [sym_column_ref] = "column_ref",
  [sym_sql_ref] = "sql_ref",
  [sym_string] = "string",
  [sym_string_content] = "string_content",
  [aux_sym__double_quoted_content] = "_double_quoted_content",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_body_repeat1] = "block_body_repeat1",
  [aux_sym_rule_repeat1] = "rule_repeat1",
  [aux_sym_ability_list_repeat1] = "ability_list_repeat1",
  [aux_sym_with_clause_repeat1] = "with_clause_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_string_content_repeat1] = "string_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_they] = anon_sym_they,
  [anon_sym_can] = anon_sym_can,
  [anon_sym_cannot] = anon_sym_cannot,
  [anon_sym_because] = anon_sym_because,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_wildcard] = sym_wildcard,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_check] = anon_sym_check,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_ATcontext] = anon_sym_ATcontext,
  [anon_sym_ATcolumn] = anon_sym_ATcolumn,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_ATsql] = anon_sym_ATsql,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_content_token1] = aux_sym_string_content_token1,
  [aux_sym__double_quoted_content_token1] = aux_sym__double_quoted_content_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_float] = sym_float,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [sym_named_binding] = sym_named_binding,
  [sym_positional] = sym_positional,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_schema_header] = sym_schema_header,
  [sym_schema_block] = sym_schema_block,
  [sym_block_body] = sym_block_body,
  [sym_rule] = sym_rule,
  [sym_condition_clause] = sym_condition_clause,
  [sym__clause] = sym__clause,
  [sym_can_clause] = sym_can_clause,
  [sym_cannot_clause] = sym_cannot_clause,
  [sym_because_clause] = sym_because_clause,
  [sym_ability_list] = sym_ability_list,
  [sym_ability] = sym_ability,
  [sym__expression] = sym__expression,
  [sym_or_expression] = sym_or_expression,
  [sym_and_expression] = sym_and_expression,
  [sym_not_expression] = sym_not_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_can_expression] = sym_can_expression,
  [sym_check_expression] = sym_check_expression,
  [sym_handle] = sym_handle,
  [sym_with_clause] = sym_with_clause,
  [sym_with_entry] = sym_with_entry,
  [sym_condition] = sym_condition,
  [sym_argument_list] = sym_argument_list,
  [sym__argument] = sym__argument,
  [sym_context_ref] = sym_context_ref,
  [sym_column_ref] = sym_column_ref,
  [sym_sql_ref] = sym_sql_ref,
  [sym_string] = sym_string,
  [sym_string_content] = sym_string_content,
  [aux_sym__double_quoted_content] = aux_sym__double_quoted_content,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_body_repeat1] = aux_sym_block_body_repeat1,
  [aux_sym_rule_repeat1] = aux_sym_rule_repeat1,
  [aux_sym_ability_list_repeat1] = aux_sym_ability_list_repeat1,
  [aux_sym_with_clause_repeat1] = aux_sym_with_clause_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_string_content_repeat1] = aux_sym_string_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_they] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_can] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cannot] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_because] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_check] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATcontext] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATcolumn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATsql] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__double_quoted_content_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_named_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_positional] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_schema_header] = {
    .visible = true,
    .named = true,
  },
  [sym_schema_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_body] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_condition_clause] = {
    .visible = true,
    .named = true,
  },
  [sym__clause] = {
    .visible = false,
    .named = true,
  },
  [sym_can_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_cannot_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_because_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_ability_list] = {
    .visible = true,
    .named = true,
  },
  [sym_ability] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_or_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_and_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_not_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_can_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_check_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_handle] = {
    .visible = true,
    .named = true,
  },
  [sym_with_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_with_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_context_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_column_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_sql_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__double_quoted_content] = {
    .visible = false,
    .named = false,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ability_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_with_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_abilities = 1,
  field_ability = 2,
  field_arguments = 3,
  field_body = 4,
  field_column = 5,
  field_condition = 6,
  field_context = 7,
  field_denial = 8,
  field_key = 9,
  field_left = 10,
  field_message = 11,
  field_name = 12,
  field_operand = 13,
  field_predicate = 14,
  field_right = 15,
  field_row = 16,
  field_schema = 17,
  field_sql = 18,
  field_target = 19,
  field_value = 20,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_abilities] = "abilities",
  [field_ability] = "ability",
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_column] = "column",
  [field_condition] = "condition",
  [field_context] = "context",
  [field_denial] = "denial",
  [field_key] = "key",
  [field_left] = "left",
  [field_message] = "message",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_predicate] = "predicate",
  [field_right] = "right",
  [field_row] = "row",
  [field_schema] = "schema",
  [field_sql] = "sql",
  [field_target] = "target",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 2},
  [7] = {.index = 7, .length = 1},
  [8] = {.index = 8, .length = 2},
  [9] = {.index = 10, .length = 2},
  [10] = {.index = 12, .length = 1},
  [11] = {.index = 13, .length = 1},
  [12] = {.index = 14, .length = 1},
  [13] = {.index = 15, .length = 1},
  [15] = {.index = 16, .length = 2},
  [16] = {.index = 18, .length = 2},
  [17] = {.index = 20, .length = 2},
  [18] = {.index = 22, .length = 3},
  [19] = {.index = 25, .length = 3},
  [20] = {.index = 28, .length = 2},
  [21] = {.index = 30, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_schema, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_condition, 1},
  [3] =
    {field_body, 1},
  [4] =
    {field_operand, 1},
  [5] =
    {field_arguments, 1},
    {field_name, 0},
  [7] =
    {field_abilities, 2},
  [8] =
    {field_left, 0},
    {field_right, 2},
  [10] =
    {field_abilities, 2},
    {field_denial, 3},
  [12] =
    {field_key, 1},
  [13] =
    {field_sql, 1},
  [14] =
    {field_message, 1},
  [15] =
    {field_schema, 0},
  [16] =
    {field_ability, 2},
    {field_target, 4},
  [18] =
    {field_predicate, 2},
    {field_target, 4},
  [20] =
    {field_column, 3},
    {field_schema, 1},
  [22] =
    {field_ability, 2},
    {field_context, 5},
    {field_target, 4},
  [25] =
    {field_context, 5},
    {field_predicate, 2},
    {field_target, 4},
  [28] =
    {field_row, 2},
    {field_schema, 0},
  [30] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [14] = {
    [1] = sym_string_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__double_quoted_content, 2,
    aux_sym__double_quoted_content,
    sym_string_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym__argument,
  sym__expression,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym__argument] = {.index = 0, .length = 10},
  [sym__expression] = {.index = 10, .length = 7},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_boolean,
    sym_column_ref,
    sym_context_ref,
    sym_float,
    sym_integer,
    sym_named_binding,
    sym_null,
    sym_positional,
    sym_sql_ref,
    sym_string,
  [10] =
    sym_and_expression,
    sym_can_expression,
    sym_check_expression,
    sym_condition,
    sym_not_expression,
    sym_or_expression,
    sym_parenthesized_expression,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '!', 25,
        '"', 34,
        '#', 47,
        '\'', 33,
        '(', 26,
        ')', 27,
        '*', 24,
        ',', 23,
        '-', 16,
        '.', 31,
        ':', 18,
        '=', 28,
        '?', 45,
        '@', 3,
        '\\', 15,
        '{', 21,
        '}', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '\'') ADVANCE(33);
      if (lookahead == '\\') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == 'c') ADVANCE(9);
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(13);
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == 'm') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 10:
      if (lookahead == 'q') ADVANCE(6);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(4);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'x') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\') ADVANCE(41);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 18:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '!', 25,
        '"', 34,
        '#', 47,
        '\'', 33,
        '(', 26,
        ')', 27,
        '*', 24,
        ',', 23,
        '-', 16,
        '.', 31,
        ':', 18,
        '=', 28,
        '?', 45,
        '@', 3,
        '{', 21,
        '}', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_wildcard);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_ATcontext);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_ATcolumn);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_ATsql);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_content_token1);
      if (lookahead == '\n') ADVANCE(37);
      if (lookahead == '\'' ||
          lookahead == '\\') ADVANCE(47);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_content_token1);
      if (lookahead == '#') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_content_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__double_quoted_content_token1);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(47);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__double_quoted_content_token1);
      if (lookahead == '#') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym__double_quoted_content_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_named_binding);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_positional);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'f', 4,
        'i', 5,
        'n', 6,
        'o', 7,
        't', 8,
        'w', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(12);
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(17);
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'h') ADVANCE(20);
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_can);
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 26:
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 31:
      if (lookahead == 'y') ADVANCE(39);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 33:
      if (lookahead == 'h') ADVANCE(41);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 36:
      if (lookahead == 'k') ADVANCE(44);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_they);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_check);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_cannot);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_because);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_they] = ACTIONS(1),
    [anon_sym_can] = ACTIONS(1),
    [anon_sym_cannot] = ACTIONS(1),
    [anon_sym_because] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_wildcard] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_check] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_ATcontext] = ACTIONS(1),
    [anon_sym_ATcolumn] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_ATsql] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_named_binding] = ACTIONS(1),
    [sym_positional] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(103),
    [sym_schema_header] = STATE(6),
    [sym_schema_block] = STATE(13),
    [sym_rule] = STATE(13),
    [sym_condition_clause] = STATE(48),
    [sym__clause] = STATE(19),
    [sym_can_clause] = STATE(19),
    [sym_cannot_clause] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(13),
    [aux_sym_rule_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_for] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_they] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_RPAREN,
    ACTIONS(15), 1,
      anon_sym_ATcontext,
    ACTIONS(17), 1,
      anon_sym_ATcolumn,
    ACTIONS(19), 1,
      anon_sym_ATsql,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      sym_integer,
    STATE(74), 1,
      sym__argument,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 4,
      sym_float,
      sym_null,
      sym_named_binding,
      sym_positional,
    STATE(83), 5,
      sym_context_ref,
      sym_column_ref,
      sym_sql_ref,
      sym_string,
      sym_boolean,
  [45] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_ATcontext,
    ACTIONS(17), 1,
      anon_sym_ATcolumn,
    ACTIONS(19), 1,
      anon_sym_ATsql,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      sym_integer,
    STATE(80), 1,
      sym__argument,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 4,
      sym_float,
      sym_null,
      sym_named_binding,
      sym_positional,
    STATE(83), 5,
      sym_context_ref,
      sym_column_ref,
      sym_sql_ref,
      sym_string,
      sym_boolean,
  [87] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_ATcontext,
    ACTIONS(17), 1,
      anon_sym_ATcolumn,
    ACTIONS(19), 1,
      anon_sym_ATsql,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      sym_integer,
    STATE(105), 1,
      sym__argument,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 4,
      sym_float,
      sym_null,
      sym_named_binding,
      sym_positional,
    STATE(83), 5,
      sym_context_ref,
      sym_column_ref,
      sym_sql_ref,
      sym_string,
      sym_boolean,
  [129] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_ATcontext,
    ACTIONS(17), 1,
      anon_sym_ATcolumn,
    ACTIONS(19), 1,
      anon_sym_ATsql,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      sym_integer,
    STATE(89), 1,
      sym__argument,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 4,
      sym_float,
      sym_null,
      sym_named_binding,
      sym_positional,
    STATE(83), 5,
      sym_context_ref,
      sym_column_ref,
      sym_sql_ref,
      sym_string,
      sym_boolean,
  [171] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_for,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_they,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      sym_condition_clause,
    STATE(55), 1,
      sym_block_body,
    STATE(77), 1,
      sym_schema_header,
    STATE(14), 3,
      sym_schema_block,
      sym_rule,
      aux_sym_source_file_repeat1,
    STATE(19), 4,
      sym__clause,
      sym_can_clause,
      sym_cannot_clause,
      aux_sym_rule_repeat1,
  [210] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_can,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      anon_sym_BANG,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      anon_sym_check,
    STATE(64), 1,
      sym__expression,
    STATE(46), 7,
      sym_or_expression,
      sym_and_expression,
      sym_not_expression,
      sym_parenthesized_expression,
      sym_can_expression,
      sym_check_expression,
      sym_condition,
  [244] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_can,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      anon_sym_BANG,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      anon_sym_check,
    STATE(68), 1,
      sym__expression,
    STATE(46), 7,
      sym_or_expression,
      sym_and_expression,
      sym_not_expression,
      sym_parenthesized_expression,
      sym_can_expression,
      sym_check_expression,
      sym_condition,
  [278] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_can,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      anon_sym_BANG,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      anon_sym_check,
    STATE(33), 1,
      sym__expression,
    STATE(46), 7,
      sym_or_expression,
      sym_and_expression,
      sym_not_expression,
      sym_parenthesized_expression,
      sym_can_expression,
      sym_check_expression,
      sym_condition,
  [312] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_can,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      anon_sym_BANG,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      anon_sym_check,
    STATE(38), 1,
      sym__expression,
    STATE(46), 7,
      sym_or_expression,
      sym_and_expression,
      sym_not_expression,
      sym_parenthesized_expression,
      sym_can_expression,
      sym_check_expression,
      sym_condition,
  [346] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_can,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      anon_sym_BANG,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      anon_sym_check,
    STATE(39), 1,
      sym__expression,
    STATE(46), 7,
      sym_or_expression,
      sym_and_expression,
      sym_not_expression,
      sym_parenthesized_expression,
      sym_can_expression,
      sym_check_expression,
      sym_condition,
  [380] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_can,
    ACTIONS(39), 1,
      anon_sym_not,
    ACTIONS(41), 1,
      anon_sym_BANG,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      anon_sym_check,
    STATE(67), 1,
      sym__expression,
    STATE(46), 7,
      sym_or_expression,
      sym_and_expression,
      sym_not_expression,
      sym_parenthesized_expression,
      sym_can_expression,
      sym_check_expression,
      sym_condition,
  [414] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_for,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_they,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(48), 1,
      sym_condition_clause,
    STATE(77), 1,
      sym_schema_header,
    STATE(15), 3,
      sym_schema_block,
      sym_rule,
      aux_sym_source_file_repeat1,
    STATE(19), 4,
      sym__clause,
      sym_can_clause,
      sym_cannot_clause,
      aux_sym_rule_repeat1,
  [447] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_for,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_they,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(48), 1,
      sym_condition_clause,
    STATE(77), 1,
      sym_schema_header,
    STATE(15), 3,
      sym_schema_block,
      sym_rule,
      aux_sym_source_file_repeat1,
    STATE(19), 4,
      sym__clause,
      sym_can_clause,
      sym_cannot_clause,
      aux_sym_rule_repeat1,
  [480] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_for,
    ACTIONS(54), 1,
      anon_sym_if,
    ACTIONS(57), 1,
      anon_sym_they,
    STATE(48), 1,
      sym_condition_clause,
    STATE(77), 1,
      sym_schema_header,
    STATE(15), 3,
      sym_schema_block,
      sym_rule,
      aux_sym_source_file_repeat1,
    STATE(19), 4,
      sym__clause,
      sym_can_clause,
      sym_cannot_clause,
      aux_sym_rule_repeat1,
  [513] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_they,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    STATE(48), 1,
      sym_condition_clause,
    STATE(18), 2,
      sym_rule,
      aux_sym_block_body_repeat1,
    STATE(19), 4,
      sym__clause,
      sym_can_clause,
      sym_cannot_clause,
      aux_sym_rule_repeat1,
  [539] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    ACTIONS(64), 1,
      anon_sym_if,
    ACTIONS(67), 1,
      anon_sym_they,
    STATE(48), 1,
      sym_condition_clause,
    STATE(17), 2,
      sym_rule,
      aux_sym_block_body_repeat1,
    STATE(19), 4,
      sym__clause,
      sym_can_clause,
      sym_cannot_clause,
      aux_sym_rule_repeat1,
  [565] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_they,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    STATE(48), 1,
      sym_condition_clause,
    STATE(17), 2,
      sym_rule,
      aux_sym_block_body_repeat1,
    STATE(19), 4,
      sym__clause,
      sym_can_clause,
      sym_cannot_clause,
      aux_sym_rule_repeat1,
  [591] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_they,
    ACTIONS(72), 4,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
    STATE(21), 4,
      sym__clause,
      sym_can_clause,
      sym_cannot_clause,
      aux_sym_rule_repeat1,
  [610] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_they,
    ACTIONS(74), 4,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
    STATE(21), 4,
      sym__clause,
      sym_can_clause,
      sym_cannot_clause,
      aux_sym_rule_repeat1,
  [629] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_they,
    ACTIONS(76), 4,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
    STATE(21), 4,
      sym__clause,
      sym_can_clause,
      sym_cannot_clause,
      aux_sym_rule_repeat1,
  [648] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      aux_sym_ability_list_repeat1,
    ACTIONS(81), 6,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_they,
      anon_sym_because,
  [666] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      aux_sym_ability_list_repeat1,
    ACTIONS(86), 6,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_they,
      anon_sym_because,
  [684] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      aux_sym_ability_list_repeat1,
    ACTIONS(90), 6,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_they,
      anon_sym_because,
  [702] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_because,
    STATE(41), 1,
      sym_because_clause,
    ACTIONS(92), 5,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_they,
  [719] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    STATE(45), 1,
      sym_argument_list,
    ACTIONS(96), 5,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [736] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 7,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_they,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [749] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 7,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_they,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [762] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 7,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_they,
      anon_sym_because,
      anon_sym_COMMA,
  [775] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 7,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_they,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [788] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 7,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_they,
      anon_sym_because,
      anon_sym_COMMA,
  [801] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 5,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_they,
  [812] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 5,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [823] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 5,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [834] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    STATE(91), 1,
      sym_string,
    ACTIONS(114), 2,
      sym_named_binding,
      sym_positional,
  [851] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 5,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [862] = 6,
    ACTIONS(118), 1,
      anon_sym_SQUOTE,
    ACTIONS(120), 1,
      aux_sym_string_content_token1,
    ACTIONS(122), 1,
      sym_escape_sequence,
    ACTIONS(124), 1,
      sym_comment,
    STATE(56), 1,
      aux_sym_string_content_repeat1,
    STATE(93), 1,
      sym_string_content,
  [881] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 5,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [892] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_and,
    ACTIONS(128), 4,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_RPAREN,
  [905] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    STATE(44), 1,
      sym_string,
    ACTIONS(132), 2,
      sym_named_binding,
      sym_positional,
  [922] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 5,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_they,
  [933] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 5,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_they,
  [944] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 5,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [955] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 5,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_they,
  [966] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 5,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [977] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 5,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [988] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 5,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [999] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_they,
    STATE(20), 4,
      sym__clause,
      sym_can_clause,
      sym_cannot_clause,
      aux_sym_rule_repeat1,
  [1012] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 5,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [1023] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 5,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [1034] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 5,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [1045] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 5,
      anon_sym_for,
      anon_sym_they,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
  [1056] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 4,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_if,
      anon_sym_they,
  [1066] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 4,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_if,
      anon_sym_they,
  [1076] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 4,
      ts_builtin_sym_end,
      anon_sym_for,
      anon_sym_if,
      anon_sym_they,
  [1086] = 5,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_SQUOTE,
    ACTIONS(164), 1,
      aux_sym_string_content_token1,
    ACTIONS(166), 1,
      sym_escape_sequence,
    STATE(60), 1,
      aux_sym_string_content_repeat1,
  [1102] = 5,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(170), 1,
      aux_sym__double_quoted_content_token1,
    ACTIONS(172), 1,
      sym_escape_sequence,
    STATE(58), 1,
      aux_sym__double_quoted_content,
  [1118] = 5,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_DQUOTE,
    ACTIONS(176), 1,
      aux_sym__double_quoted_content_token1,
    ACTIONS(179), 1,
      sym_escape_sequence,
    STATE(58), 1,
      aux_sym__double_quoted_content,
  [1134] = 5,
    ACTIONS(118), 1,
      anon_sym_DQUOTE,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(170), 1,
      aux_sym__double_quoted_content_token1,
    ACTIONS(172), 1,
      sym_escape_sequence,
    STATE(57), 1,
      aux_sym__double_quoted_content,
  [1150] = 5,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_SQUOTE,
    ACTIONS(184), 1,
      aux_sym_string_content_token1,
    ACTIONS(187), 1,
      sym_escape_sequence,
    STATE(60), 1,
      aux_sym_string_content_repeat1,
  [1166] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(23), 1,
      sym_ability,
    STATE(25), 1,
      sym_ability_list,
    ACTIONS(190), 2,
      sym_wildcard,
      sym_identifier,
  [1180] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(23), 1,
      sym_ability,
    STATE(32), 1,
      sym_ability_list,
    ACTIONS(190), 2,
      sym_wildcard,
      sym_identifier,
  [1194] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(29), 1,
      sym_ability,
    ACTIONS(190), 2,
      sym_wildcard,
      sym_identifier,
  [1205] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_and,
    ACTIONS(192), 1,
      anon_sym_they,
    ACTIONS(194), 1,
      anon_sym_or,
  [1218] = 3,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_escape_sequence,
    ACTIONS(196), 2,
      anon_sym_DQUOTE,
      aux_sym__double_quoted_content_token1,
  [1229] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_argument_list_repeat1,
  [1242] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_and,
    ACTIONS(194), 1,
      anon_sym_or,
    ACTIONS(204), 1,
      anon_sym_for,
  [1255] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_and,
    ACTIONS(194), 1,
      anon_sym_or,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
  [1268] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
    ACTIONS(210), 2,
      anon_sym_RPAREN,
      anon_sym_with,
  [1279] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
    ACTIONS(214), 1,
      anon_sym_with,
    STATE(100), 1,
      sym_with_clause,
  [1292] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_argument_list_repeat1,
  [1305] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_with,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    STATE(104), 1,
      sym_with_clause,
  [1318] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym_with_clause_repeat1,
  [1331] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      aux_sym_argument_list_repeat1,
  [1344] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_with_clause_repeat1,
  [1357] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_with_clause_repeat1,
  [1370] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    STATE(55), 1,
      sym_block_body,
  [1380] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_identifier,
    STATE(73), 1,
      sym_with_entry,
  [1390] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_identifier,
    STATE(70), 1,
      sym_handle,
  [1400] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1408] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_can,
    ACTIONS(242), 1,
      anon_sym_cannot,
  [1418] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_identifier,
    STATE(72), 1,
      sym_handle,
  [1428] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1436] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_identifier,
    STATE(90), 1,
      sym_with_entry,
  [1446] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1454] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1462] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1470] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 2,
      anon_sym_RPAREN,
      anon_sym_with,
  [1478] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1486] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1494] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1502] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_identifier,
  [1509] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_SQUOTE,
  [1516] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym_identifier,
  [1523] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_identifier,
  [1530] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      sym_identifier,
  [1537] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_for,
  [1544] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_identifier,
  [1551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_LPAREN,
  [1558] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
  [1565] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_LPAREN,
  [1572] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_EQ,
  [1579] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      ts_builtin_sym_end,
  [1586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_RPAREN,
  [1593] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
  [1600] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_DOT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 87,
  [SMALL_STATE(5)] = 129,
  [SMALL_STATE(6)] = 171,
  [SMALL_STATE(7)] = 210,
  [SMALL_STATE(8)] = 244,
  [SMALL_STATE(9)] = 278,
  [SMALL_STATE(10)] = 312,
  [SMALL_STATE(11)] = 346,
  [SMALL_STATE(12)] = 380,
  [SMALL_STATE(13)] = 414,
  [SMALL_STATE(14)] = 447,
  [SMALL_STATE(15)] = 480,
  [SMALL_STATE(16)] = 513,
  [SMALL_STATE(17)] = 539,
  [SMALL_STATE(18)] = 565,
  [SMALL_STATE(19)] = 591,
  [SMALL_STATE(20)] = 610,
  [SMALL_STATE(21)] = 629,
  [SMALL_STATE(22)] = 648,
  [SMALL_STATE(23)] = 666,
  [SMALL_STATE(24)] = 684,
  [SMALL_STATE(25)] = 702,
  [SMALL_STATE(26)] = 719,
  [SMALL_STATE(27)] = 736,
  [SMALL_STATE(28)] = 749,
  [SMALL_STATE(29)] = 762,
  [SMALL_STATE(30)] = 775,
  [SMALL_STATE(31)] = 788,
  [SMALL_STATE(32)] = 801,
  [SMALL_STATE(33)] = 812,
  [SMALL_STATE(34)] = 823,
  [SMALL_STATE(35)] = 834,
  [SMALL_STATE(36)] = 851,
  [SMALL_STATE(37)] = 862,
  [SMALL_STATE(38)] = 881,
  [SMALL_STATE(39)] = 892,
  [SMALL_STATE(40)] = 905,
  [SMALL_STATE(41)] = 922,
  [SMALL_STATE(42)] = 933,
  [SMALL_STATE(43)] = 944,
  [SMALL_STATE(44)] = 955,
  [SMALL_STATE(45)] = 966,
  [SMALL_STATE(46)] = 977,
  [SMALL_STATE(47)] = 988,
  [SMALL_STATE(48)] = 999,
  [SMALL_STATE(49)] = 1012,
  [SMALL_STATE(50)] = 1023,
  [SMALL_STATE(51)] = 1034,
  [SMALL_STATE(52)] = 1045,
  [SMALL_STATE(53)] = 1056,
  [SMALL_STATE(54)] = 1066,
  [SMALL_STATE(55)] = 1076,
  [SMALL_STATE(56)] = 1086,
  [SMALL_STATE(57)] = 1102,
  [SMALL_STATE(58)] = 1118,
  [SMALL_STATE(59)] = 1134,
  [SMALL_STATE(60)] = 1150,
  [SMALL_STATE(61)] = 1166,
  [SMALL_STATE(62)] = 1180,
  [SMALL_STATE(63)] = 1194,
  [SMALL_STATE(64)] = 1205,
  [SMALL_STATE(65)] = 1218,
  [SMALL_STATE(66)] = 1229,
  [SMALL_STATE(67)] = 1242,
  [SMALL_STATE(68)] = 1255,
  [SMALL_STATE(69)] = 1268,
  [SMALL_STATE(70)] = 1279,
  [SMALL_STATE(71)] = 1292,
  [SMALL_STATE(72)] = 1305,
  [SMALL_STATE(73)] = 1318,
  [SMALL_STATE(74)] = 1331,
  [SMALL_STATE(75)] = 1344,
  [SMALL_STATE(76)] = 1357,
  [SMALL_STATE(77)] = 1370,
  [SMALL_STATE(78)] = 1380,
  [SMALL_STATE(79)] = 1390,
  [SMALL_STATE(80)] = 1400,
  [SMALL_STATE(81)] = 1408,
  [SMALL_STATE(82)] = 1418,
  [SMALL_STATE(83)] = 1428,
  [SMALL_STATE(84)] = 1436,
  [SMALL_STATE(85)] = 1446,
  [SMALL_STATE(86)] = 1454,
  [SMALL_STATE(87)] = 1462,
  [SMALL_STATE(88)] = 1470,
  [SMALL_STATE(89)] = 1478,
  [SMALL_STATE(90)] = 1486,
  [SMALL_STATE(91)] = 1494,
  [SMALL_STATE(92)] = 1502,
  [SMALL_STATE(93)] = 1509,
  [SMALL_STATE(94)] = 1516,
  [SMALL_STATE(95)] = 1523,
  [SMALL_STATE(96)] = 1530,
  [SMALL_STATE(97)] = 1537,
  [SMALL_STATE(98)] = 1544,
  [SMALL_STATE(99)] = 1551,
  [SMALL_STATE(100)] = 1558,
  [SMALL_STATE(101)] = 1565,
  [SMALL_STATE(102)] = 1572,
  [SMALL_STATE(103)] = 1579,
  [SMALL_STATE(104)] = 1586,
  [SMALL_STATE(105)] = 1593,
  [SMALL_STATE(106)] = 1600,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_body_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_body_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ability_list_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ability_list_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ability_list, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ability_list, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cannot_clause, 3, 0, 7),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 1, 0, 2),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 14),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ability, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_can_clause, 3, 0, 7),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_not_expression, 2, 0, 5),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_and_expression, 3, 0, 8),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_or_expression, 3, 0, 8),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cannot_clause, 4, 0, 9),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema_header, 2, 0, 1),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_because_clause, 2, 0, 12),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 2, 0, 6),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_can_expression, 6, 0, 15),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_check_expression, 6, 0, 16),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_can_expression, 7, 0, 18),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_check_expression, 7, 0, 19),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_body, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_body, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema_block, 2, 0, 4),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_content, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__double_quoted_content, 2, 0, 0),
  [176] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__double_quoted_content, 2, 0, 0), SHIFT_REPEAT(65),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__double_quoted_content, 2, 0, 0), SHIFT_REPEAT(65),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_content_repeat1, 2, 0, 0),
  [184] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_content_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_content_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition_clause, 2, 0, 3),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__double_quoted_content, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__double_quoted_content, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handle, 1, 0, 13),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_with_clause, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_with_clause, 3, 0, 0),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_with_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_with_clause_repeat1, 2, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 1, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_ref, 4, 0, 17),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context_ref, 2, 0, 10),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handle, 4, 0, 20),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_with_entry, 3, 0, 21),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sql_ref, 2, 0, 11),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [280] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_warrant(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "warrant",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
